# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/binita/Downloads/wt-3.2.2-rc1/examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/binita/Downloads/wt-3.2.2-rc1/examples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(CMAKE_COMMAND) -E cmake_progress_start /home/binita/Downloads/wt-3.2.2-rc1/examples/CMakeFiles /home/binita/Downloads/wt-3.2.2-rc1/examples/feature/auth1/CMakeFiles/progress.marks
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f CMakeFiles/Makefile2 feature/auth1/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/binita/Downloads/wt-3.2.2-rc1/examples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f CMakeFiles/Makefile2 feature/auth1/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f CMakeFiles/Makefile2 feature/auth1/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f CMakeFiles/Makefile2 feature/auth1/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
feature/auth1/CMakeFiles/auth1.wt.dir/rule:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f CMakeFiles/Makefile2 feature/auth1/CMakeFiles/auth1.wt.dir/rule
.PHONY : feature/auth1/CMakeFiles/auth1.wt.dir/rule

# Convenience name for target.
auth1.wt: feature/auth1/CMakeFiles/auth1.wt.dir/rule
.PHONY : auth1.wt

# fast build rule for target.
auth1.wt/fast:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/build
.PHONY : auth1.wt/fast

# target to build an object file
Auth1.o:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/Auth1.o
.PHONY : Auth1.o

# target to preprocess a source file
Auth1.i:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/Auth1.i
.PHONY : Auth1.i

# target to generate assembly for a file
Auth1.s:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/Auth1.s
.PHONY : Auth1.s

# target to build an object file
model/Session.o:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/Session.o
.PHONY : model/Session.o

# target to preprocess a source file
model/Session.i:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/Session.i
.PHONY : model/Session.i

# target to generate assembly for a file
model/Session.s:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/Session.s
.PHONY : model/Session.s

# target to build an object file
model/User.o:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/User.o
.PHONY : model/User.o

# target to preprocess a source file
model/User.i:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/User.i
.PHONY : model/User.i

# target to generate assembly for a file
model/User.s:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(MAKE) -f feature/auth1/CMakeFiles/auth1.wt.dir/build.make feature/auth1/CMakeFiles/auth1.wt.dir/model/User.s
.PHONY : model/User.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... auth1.wt"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Auth1.o"
	@echo "... Auth1.i"
	@echo "... Auth1.s"
	@echo "... model/Session.o"
	@echo "... model/Session.i"
	@echo "... model/Session.s"
	@echo "... model/User.o"
	@echo "... model/User.i"
	@echo "... model/User.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/binita/Downloads/wt-3.2.2-rc1/examples && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

